In [1]:
import glob
import scipy.io as si

In [5]:
length = 0
for name in glob.glob('E:\LAB\ScaleMind\Data_ECG\TrainingSet*\*\*'):
    mat = si.loadmat(name)
    x = mat.get("ECG")
    a = x[0][0]
    length = length + len(a[2][1])
print(length/6788)   

8078.592810842663


In [6]:
path_test = glob.glob('E:\LAB\ScaleMind\Data_ECG\TrainingSet*\*\*')
path_test[0]

'E:\\LAB\\ScaleMind\\Data_ECG\\TrainingSet1\\TrainingSet1\\A0001.mat'

In [43]:
mat = si.loadmat(path_test[0])
x = mat.get("ECG")
a = x[0][0]
a

(array(['Male'], dtype='<U4'), array([[74]], dtype=uint8), array([[ 0.0282288 ,  0.0392288 ,  0.0452288 , ...,  0.2582288 ,
         0.2592288 ,  0.2592288 ],
       [ 0.00672947,  0.01072947,  0.01472947, ...,  0.24772947,
         0.24872947,  0.24972947],
       [-0.02149933, -0.02849933, -0.03049933, ..., -0.01049933,
        -0.01049933, -0.00949933],
       ...,
       [-0.11200653, -0.11000653, -0.10800653, ...,  0.19399347,
         0.19399347,  0.19499347],
       [-0.5959572 , -0.5899572 , -0.5819572 , ...,  0.3070428 ,
         0.3070428 ,  0.3070428 ],
       [-0.01558507, -0.00658507,  0.00241493, ...,  0.21341493,
         0.21441493,  0.21441493]]))

In [9]:
test = a[2][:, -72000: ]
test

array([[ 0.0282288 ,  0.0392288 ,  0.0452288 , ...,  0.2582288 ,
         0.2592288 ,  0.2592288 ],
       [ 0.00672947,  0.01072947,  0.01472947, ...,  0.24772947,
         0.24872947,  0.24972947],
       [-0.02149933, -0.02849933, -0.03049933, ..., -0.01049933,
        -0.01049933, -0.00949933],
       ...,
       [-0.11200653, -0.11000653, -0.10800653, ...,  0.19399347,
         0.19399347,  0.19499347],
       [-0.5959572 , -0.5899572 , -0.5819572 , ...,  0.3070428 ,
         0.3070428 ,  0.3070428 ],
       [-0.01558507, -0.00658507,  0.00241493, ...,  0.21341493,
         0.21441493,  0.21441493]])

In [10]:
for x in test:
    print(len(x))

7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500
7500


In [11]:
test.T

array([[ 0.0282288 ,  0.00672947, -0.02149933, ..., -0.11200653,
        -0.5959572 , -0.01558507],
       [ 0.0392288 ,  0.01072947, -0.02849933, ..., -0.11000653,
        -0.5899572 , -0.00658507],
       [ 0.0452288 ,  0.01472947, -0.03049933, ..., -0.10800653,
        -0.5819572 ,  0.00241493],
       ...,
       [ 0.2582288 ,  0.24772947, -0.01049933, ...,  0.19399347,
         0.3070428 ,  0.21341493],
       [ 0.2592288 ,  0.24872947, -0.01049933, ...,  0.19399347,
         0.3070428 ,  0.21441493],
       [ 0.2592288 ,  0.24972947, -0.00949933, ...,  0.19499347,
         0.3070428 ,  0.21441493]])

In [76]:
a[2][:4,:3]

array([[ 0.0282288 ,  0.0392288 ,  0.0452288 ],
       [ 0.00672947,  0.01072947,  0.01472947],
       [-0.02149933, -0.02849933, -0.03049933],
       [-0.01749067, -0.02449067, -0.02949067]])

In [77]:
a[2]>3

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [79]:
import numpy as np
x=np.arange(6).reshape(2,3)
print(x)
np.argwhere(x)

[[0 1 2]
 [3 4 5]]


array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [88]:
y = a[2][0]
b = np.argwhere(np.abs(y)>0.1)
b = b[:,0]
print(b)

[[  16]
 [  17]
 [  18]
 ...
 [7497]
 [7498]
 [7499]]
